### ISSUE TITLE
right axis title flipped

### ISSUE THREAD

**Issue by ukos-git** [plotly/Igor-Pro-Graph-Converter#21]
![Screenshot from 2019-05-03 16-24-38](https://user-images.githubusercontent.com/16167358/57143808-00700300-6dc0-11e9-966e-fa02a9ea504e.png)![Screenshot from 2019-05-03 16-24-44](https://user-images.githubusercontent.com/16167358/57143809-00700300-6dc0-11e9-9ef4-403fca3bf8f6.png)

**Comment by alexcjohnson** [comment]
Currently not configurable in plotly.js, AFAIK. Igor seems to be distinctly in the minority here, nearly every other [example I see](https://www.google.com/search?q=multiple+y+axes&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiP79qK2__hAhUBrZ4KHWJpBHYQ_AUIDigB&biw=1234&bih=570#imgrc=_) has vertical text always rotated CCW, whether the axis is on the left or right.

**Comment by ukos-git** [comment]
That is an overwhelming majority of graphs on google that has the axis "flipped". I am so used to Igor's "right Axis" that I find it confusing seeing it displayed this way.

**Comment by ukos-git** [comment]
Closing as unfixable
